export const PROBLEM_BASE_URL = 'https://www.jhipster.tech/problem';
export const EMAIL_ALREADY_USED_TYPE = PROBLEM_BASE_URL + '/email-already-used';
export const LOGIN_ALREADY_USED_TYPE = PROBLEM_BASE_URL + '/login-already-used';
export const EMAIL_NOT_FOUND_TYPE = PROBLEM_BASE_URL + '/email-not-found';
export const INVALID_AUTHORITY = PROBLEM_BASE_URL + '/invalid-authority';
export const NO_HARNESS_AVAILABLE = PROBLEM_BASE_URL + '/no-harness-available';
export const NO_WETSUIT_AVAILABLE = PROBLEM_BASE_URL + '/no-wetsuit-available';
export const ALREADY_RESERVED = PROBLEM_BASE_URL + '/already-reserved';
export const DUE_DATE_PASSED = PROBLEM_BASE_URL + '/due-date-passed';
